alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cleanzone='find . -name "*Zone.Identifier" -delete'
alias cp='cp -i'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log --oneline --graph --decorate --all'
alias grep='grep --color=auto'
alias gs='git status -sb'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias mv='mv -i'
alias rm='rm -i'
alias shfmt-format='shfmt -i 2 -bn -ci -sr -w .'
alias dpot="docker start portainer && echo 'Portainer started at https://localhost:9443'"
alias dpotstop="docker stop portainer && echo 'Portainer stopped'"
